"""
Configuration management for documentation generation.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List


@dataclass
class DocumentationConfig:
    """Configuration for documentation generation process."""

    project_root: Path
    staging_dir: Path
    readme_path: Path
    src_dir: Path

    # Type mappings for Java to schema types
    type_mappings: Dict[str, str]

    # Tool categories for organization
    tool_categories: Dict[str, List[str]]

    # Section markers for README updates
    section_markers: Dict[str, Dict[str, str]]

    @classmethod
    def from_project_root(cls, root: Path) -> 'DocumentationConfig':
        """Create configuration from project root directory."""
        if isinstance(root, str):
            root = Path(root)

        project_root = root.resolve()

        return cls(
            project_root=project_root,
            staging_dir=project_root / "staging",
            readme_path=project_root / "README.md",
            src_dir=project_root / "src" / "main" / "java" / "com" / "jasonriddle" / "mcp",
            type_mappings={
                'String': 'string',
                'List<String>': 'array',
                'List<Map<String, Object>>': 'array',
                'List<Map<String, String>>': 'array',
                'Map<String, Object>': 'object',
                'Map<String, String>': 'object',
                'Map<String,Object>': 'object',
                'Map<String,String>': 'object',
                'List<Map<String,Object>>': 'array',
                'List<Map<String,String>>': 'array',
                'boolean': 'boolean',
                'int': 'number',
                'long': 'number'
            },
            tool_categories={
                'Entity Management': ['create_entities', 'delete_entities'],
                'Relationship Management': ['create_relations', 'delete_relations'],
                'Observation Management': ['add_observations', 'delete_observations'],
                'Graph Operations': ['read_graph', 'search_nodes', 'open_nodes']
            },
            section_markers={
                'tools': {
                    'start_pattern': r'<!--- Tools generated by .* -->',
                    'end_marker': '<!--- End of tools generated section -->',
                    'new_start_marker': '<!--- Tools generated by update-docs.py -->'
                },
                'resources': {
                    'start_pattern': r'<!--- Resources generated by .* -->',
                    'end_marker': '<!--- End of resources generated section -->',
                    'new_start_marker': '<!--- Resources generated by update-docs.py -->'
                },
                'prompts': {
                    'start_pattern': r'<!--- Prompts generated by .* -->',
                    'end_marker': '<!--- End of prompts generated section -->',
                    'new_start_marker': '<!--- Prompts generated by update-docs.py -->'
                }
            }
        )

    def validate(self) -> List[str]:
        """Validate configuration and return list of errors."""
        errors = []

        if not self.project_root.exists():
            errors.append(f"Project root does not exist: {self.project_root}")

        if not self.readme_path.exists():
            errors.append(f"README.md does not exist: {self.readme_path}")

        if not self.src_dir.exists():
            errors.append(f"Source directory does not exist: {self.src_dir}")

        # Check for required Java files
        tools_file = self.src_dir / "McpMemoryTools.java"
        resources_file = self.src_dir / "McpMemoryResources.java"

        if not tools_file.exists():
            errors.append(f"Tools file does not exist: {tools_file}")

        if not resources_file.exists():
            errors.append(f"Resources file does not exist: {resources_file}")

        return errors

    def ensure_staging_dir(self) -> None:
        """Ensure staging directory exists."""
        self.staging_dir.mkdir(parents=True, exist_ok=True)

    def get_tools_file_path(self) -> Path:
        """Get path to McpMemoryTools.java file."""
        return self.src_dir / "McpMemoryTools.java"

    def get_resources_file_path(self) -> Path:
        """Get path to McpMemoryResources.java file."""
        return self.src_dir / "McpMemoryResources.java"

    def simplify_java_type(self, java_type: str) -> str:
        """Convert Java type to simplified schema type."""
        java_type = java_type.strip()
        return self.type_mappings.get(java_type, java_type.lower())

    def categorize_tool(self, tool_name: str) -> str:
        """Determine category for a tool based on its name."""
        tool_name = tool_name.replace('memory.', '').replace('memory_', '')

        for category, keywords in self.tool_categories.items():
            if any(keyword in tool_name for keyword in keywords):
                return category

        return 'Other'
