---
creation_rules:
  - path_regex: \.env$
    age: >-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7CDE4+VPLE2z6iMBCUMaZywa0K3PLB2GRGoaquyIiZ,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXcgg57LiamkDH4xKx1FQoISOtIvBGPmf2bY1orOi54,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM8Vl1+GeEfIDhQR8L7paGOTnY77ns/5OTipjhm+6QOs,
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRQ8BNagNC+jw7A/Gxb0kQ3FfGQ+J3j5E8WYiRNjMmNqfO8AVW5E4pPGQmbf+LGDPi9/DTYC2FmilHu9kcI20T4RH3NfPsBUyDWoUwusOOuEhwP+egn/CSOkJ8+WpaedWwCpBVw7fHjiDcfoN3jHSHL2VAhHxgbbObpeTPWJ65SuejaDvb7d8m1337BRq7v99A65nrdcttBlXhYaJ8FAuQW33DULm9C+uXQFl5tkSMS2TQOXlXPgpx1K5I9sYM+AqU5YrSU6FoezV8uXZEBu2w2QierDt+H32oNwTtfVJ6OjEiwupT7EI406Ad41Yqt6pGqkNzk6Nwk64eH1q+3/j66UCS3xDEQUvIBKp0liEvPDfp/D6KLK5IQjGV9d1wB7Chb0POG/wHLpVKUXr0MCw7PwlaD3lvAdZ0SPjvfkRSaDghr/ahf8QvJ/4qf8fGjzYD+nMH8In4T9HDEUYa4P39YeeKc1KRuHTF4Z8DrgH7VuRPPOTxoNPK6rdubPXtUmb5uh4FVUN401XGGDDQg8k1Rqdf5Gs/ocR0AIh/0LD8dDvlRpTK/htsvdPx5U07MKYpEEchot89vwdlRyvOGiqidQT+FDog89qa6/NrCDend6UrJNPXNwdIdNPIwwPj5VC6GqIJo2JxjiAuouScB2S8jJcxNkvFm5LfIwGF+f5tQw==
