"""
Simple test runner for main orchestrator.
"""

import sys
import tempfile
from pathlib import Path

# Add parent directory to path to import our modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from update_docs.config import DocumentationConfig
from update_docs.main import DocumentationOrchestrator


def create_test_java_files(temp_dir: Path):
    """Create minimal test Java files."""
    src_dir = temp_dir / "src" / "main" / "java" / "com" / "jasonriddle" / "mcp"
    src_dir.mkdir(parents=True)

    # Create minimal tools file
    tools_file = src_dir / "McpMemoryTools.java"
    tools_file.write_text('''
public class McpMemoryTools {
    @Tool(name = "memory.test_tool", description = "A test tool")
    public String testTool() {
        return "test";
    }
}
''')

    # Create minimal resources file
    resources_file = src_dir / "McpMemoryResources.java"
    resources_file.write_text('''
public class McpMemoryResources {
    @Resource(uri = "memory://test")
    TextResourceContents testResource() {
        return null;
    }
}
''')

    return src_dir


def create_test_readme(temp_dir: Path):
    """Create a test README with proper markers."""
    readme = temp_dir / "README.md"
    readme.write_text('''# Test Project

## MCP Tools

<!--- Tools generated by update-docs.py --->
Existing tools content
<!--- End of tools generated section --->

## MCP Resources

<!--- Resources generated by update-docs.py --->
Existing resources content
<!--- End of resources generated section --->

## MCP Prompts

<!--- Prompts generated by update-docs.py --->
Existing prompts content
<!--- End of prompts generated section --->
''')
    return readme


def test_orchestrator_initialization():
    """Test DocumentationOrchestrator initialization."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Check that all components are initialized
        assert orchestrator.config == config
        assert orchestrator.file_manager is not None
        assert orchestrator.validator is not None
        assert orchestrator.java_extractor is not None
        assert orchestrator.regex_extractor is not None
        assert orchestrator.tools_generator is not None
        assert orchestrator.resources_generator is not None
        assert orchestrator.prompts_generator is not None

    print("✓ test_orchestrator_initialization")


def test_extract_data():
    """Test data extraction functionality."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_java_files(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        data = orchestrator._extract_data()

        # Should extract data successfully
        assert isinstance(data, dict)
        assert 'tools' in data
        assert 'resources' in data
        assert 'prompts' in data

        # Should have at least one tool and resource from test files
        assert len(data['tools']) >= 1
        assert len(data['resources']) >= 1

    print("✓ test_extract_data")


def test_generate_content():
    """Test content generation functionality."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Create sample data
        sample_data = {
            'tools': [
                {
                    'name': 'memory.test_tool',
                    'title': 'Test Tool',
                    'description': 'A test tool.',
                    'method_name': 'testTool',
                    'return_type': 'String',
                    'parameters': [],
                    'read_only': False
                }
            ],
            'resources': [
                {
                    'uri': 'memory://test',
                    'title': 'Memory Test',
                    'description': 'A test resource.',
                    'method_name': 'testResource'
                }
            ],
            'prompts': []
        }

        content = orchestrator._generate_content(sample_data)

        # Should generate content for tools and resources
        assert isinstance(content, dict)
        assert 'tools' in content
        assert 'resources' in content
        assert len(content['tools']) > 0
        assert len(content['resources']) > 0

    print("✓ test_generate_content")


def test_validate_content():
    """Test content validation functionality."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Test with valid content
        valid_content = {
            'tools': '<details><summary><b>Tools</b></summary>\n\n- Tool 1\n\n</details>',
            'resources': '<details><summary><b>Resources</b></summary>\n\n- Resource 1\n\n</details>'
        }

        result = orchestrator._validate_content(valid_content)
        assert result == True  # Should pass validation

        # Test with invalid content
        invalid_content = {
            'tools': '<details><summary><b>Tools</b></summary>\n\n- Tool 1\n\n',  # Missing closing tag
        }

        result = orchestrator._validate_content(invalid_content)
        assert result == False  # Should fail validation

    print("✓ test_validate_content")


def test_dry_run_pipeline():
    """Test running pipeline in dry run mode."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_java_files(temp_path)
        create_test_readme(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Run dry run
        result = orchestrator.run_full_pipeline(dry_run=True)

        # Should complete successfully
        assert result == True

        # Original README should be unchanged
        readme = temp_path / "README.md"
        content = readme.read_text()
        assert "Existing tools content" in content
        assert "Existing resources content" in content

    print("✓ test_dry_run_pipeline")


def test_full_pipeline():
    """Test running full pipeline with changes."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_java_files(temp_path)
        create_test_readme(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Ensure staging directory exists
        config.ensure_staging_dir()

        # Run full pipeline
        result = orchestrator.run_full_pipeline(dry_run=False)

        # Should complete successfully
        assert result == True

        # README should be updated
        readme = temp_path / "README.md"
        content = readme.read_text()

        # Should contain generated content markers
        assert "<!-- NOTE: This has been generated via update-docs.py" in content

        # Should not contain old content
        assert "Existing tools content" not in content
        assert "Existing resources content" not in content

    print("✓ test_full_pipeline")


def test_update_single_section():
    """Test updating a single section."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_java_files(temp_path)
        create_test_readme(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Ensure staging directory exists
        config.ensure_staging_dir()

        # Update only tools section
        result = orchestrator.update_single_section('tools', dry_run=False)

        # Should complete successfully
        assert result == True

        # README should have updated tools section
        readme = temp_path / "README.md"
        content = readme.read_text()

        # Tools section should be updated
        assert "<!-- NOTE: This has been generated via update-docs.py" in content

        # Resources section should still have old content
        assert "Existing resources content" in content

    print("✓ test_update_single_section")


def test_invalid_section():
    """Test updating an invalid section."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Try to update invalid section
        result = orchestrator.update_single_section('invalid_section')

        # Should fail
        assert result == False

    print("✓ test_invalid_section")


def test_orchestrator_error_handling():
    """Test error handling in orchestrator."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        # Don't create Java files - this should cause extraction to return empty data

        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Try to extract data from non-existent files
        data = orchestrator._extract_data()

        # Should handle gracefully and return empty data
        assert isinstance(data, dict)
        # May be empty or have empty lists
        assert data.get('tools', []) == []
        assert data.get('resources', []) == []

    print("✓ test_orchestrator_error_handling")


def test_orchestrator_integration():
    """Test integration of all orchestrator components."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_java_files(temp_path)
        create_test_readme(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        orchestrator = DocumentationOrchestrator(config)

        # Test the complete workflow
        # 1. Extract data
        data = orchestrator._extract_data()
        assert len(data['tools']) > 0

        # 2. Generate content
        content = orchestrator._generate_content(data)
        assert 'tools' in content
        assert len(content['tools']) > 0

        # 3. Validate content
        is_valid = orchestrator._validate_content(content)
        assert is_valid == True

        # 4. Preview changes
        orchestrator._preview_changes(content)

    print("✓ test_orchestrator_integration")


def run_all_tests():
    """Run all test functions."""
    test_functions = [
        test_orchestrator_initialization,
        test_extract_data,
        test_generate_content,
        test_validate_content,
        test_dry_run_pipeline,
        test_full_pipeline,
        test_update_single_section,
        test_invalid_section,
        test_orchestrator_error_handling,
        test_orchestrator_integration,
    ]

    passed = 0
    failed = 0

    for test_func in test_functions:
        try:
            test_func()
            passed += 1
        except Exception as e:
            print(f"✗ {test_func.__name__}: {e}")
            failed += 1

    print(f"\nTest Results: {passed} passed, {failed} failed")
    return failed == 0


if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)
