"""
Simple test runner for file manager.
"""

import sys
import tempfile
from pathlib import Path
from unittest.mock import patch, Mock

# Add parent directory to path to import our modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from update_docs.config import DocumentationConfig
from update_docs.file_manager import (
    FileManager, SectionManager, BackupManager, FileManagerError
)


def create_test_readme_content():
    """Create test README content with section markers."""
    return """# Test Project

This is a test project.

## Features

<!--- Tools generated by update-docs.py --->
Old tools content here
<!--- End of tools generated section --->

## Resources

<!--- Resources generated by update-docs.py --->
Old resources content here
<!--- End of resources generated section --->

## Installation

Some installation instructions.
"""


def create_test_project_structure(temp_dir: Path) -> Path:
    """Create test project structure."""
    # Create basic directories
    (temp_dir / "src" / "main" / "java" / "com" / "jasonriddle" / "mcp").mkdir(parents=True)
    (temp_dir / "scripts").mkdir()

    # Create README with sections
    readme_content = create_test_readme_content()
    (temp_dir / "README.md").write_text(readme_content)

    return temp_dir


def test_file_manager_initialization():
    """Test FileManager initialization."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        assert file_manager.config == config
        assert file_manager.backup_dir is None
        assert len(file_manager.staging_files) == 0
        assert len(file_manager.operations_log) == 0

    print("✓ test_file_manager_initialization")


def test_create_staging_environment():
    """Test staging environment creation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        # First call should create directory
        staging_dir = file_manager.create_staging_environment()
        assert staging_dir.exists()
        assert staging_dir.is_dir()
        assert file_manager.backup_dir == staging_dir
        assert len(file_manager.operations_log) == 1

        # Second call should return same directory
        staging_dir2 = file_manager.create_staging_environment()
        assert staging_dir2 == staging_dir
        assert len(file_manager.operations_log) == 1  # No additional log entry

    print("✓ test_create_staging_environment")


def test_create_backup():
    """Test file backup creation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        readme_path = temp_path / "README.md"
        original_content = readme_path.read_text()

        # Create backup
        backup_path = file_manager.create_backup(readme_path)

        assert backup_path.exists()
        assert backup_path.read_text() == original_content
        assert file_manager.backup_dir is not None
        assert len(file_manager.operations_log) == 2  # staging + backup

        # Test backup of non-existent file
        try:
            file_manager.create_backup(temp_path / "nonexistent.txt")
            assert False, "Should have raised FileManagerError"
        except FileManagerError:
            pass  # Expected

    print("✓ test_create_backup")


def test_create_staging_file():
    """Test staging file creation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        readme_path = temp_path / "README.md"
        new_content = "New content for testing"

        # Create staging file
        staging_path = file_manager.create_staging_file(readme_path, new_content)

        assert staging_path.exists()
        assert staging_path.read_text() == new_content
        assert str(readme_path) in file_manager.staging_files
        assert file_manager.staging_files[str(readme_path)] == staging_path
        assert len(file_manager.operations_log) == 2  # staging + file creation

    print("✓ test_create_staging_file")


def test_update_readme_section():
    """Test README section updating."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        new_tools_content = "New tools content here"

        # Update tools section
        result = file_manager.update_readme_section('tools', new_tools_content)

        assert result == True
        assert len(file_manager.staging_files) == 1

        # Check staging file content
        readme_path = temp_path / "README.md"
        staging_content = file_manager.get_staging_preview(readme_path)

        assert staging_content is not None
        assert new_tools_content in staging_content
        assert "Old tools content here" not in staging_content
        assert "<!--- Tools generated by update-docs.py --->" in staging_content
        assert "<!--- End of tools generated section --->" in staging_content

        # Test unknown section
        try:
            file_manager.update_readme_section('unknown', 'content')
            assert False, "Should have raised FileManagerError"
        except FileManagerError:
            pass  # Expected

    print("✓ test_update_readme_section")


def test_replace_section_content():
    """Test section content replacement logic."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        content = """Before
<!-- START TEST -->
Old content
<!-- END TEST -->
After"""

        new_content = "New content"

        result = file_manager._replace_section_content(
            content, "<!-- START TEST -->", "<!-- END TEST -->", new_content
        )

        assert "New content" in result
        assert "Old content" not in result
        assert "Before" in result
        assert "After" in result
        assert "<!-- START TEST -->" in result
        assert "<!-- END TEST -->" in result

        # Test missing markers
        try:
            file_manager._replace_section_content(
                content, "<!-- MISSING -->", "<!-- END TEST -->", new_content
            )
            assert False, "Should have raised FileManagerError"
        except FileManagerError:
            pass  # Expected

    print("✓ test_replace_section_content")


def test_validate_staging_files():
    """Test staging file validation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        # Create valid staging file
        readme_path = temp_path / "README.md"
        file_manager.update_readme_section('tools', 'New tools content')

        # Validation should pass
        errors = file_manager.validate_staging_files()
        assert len(errors) == 0

        # Create invalid staging file (empty)
        staging_path = list(file_manager.staging_files.values())[0]
        staging_path.write_text("")

        errors = file_manager.validate_staging_files()
        assert len(errors) > 0
        assert any("empty" in error.lower() for error in errors)

    print("✓ test_validate_staging_files")


def test_apply_changes():
    """Test applying staging changes to original files."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        readme_path = temp_path / "README.md"
        original_content = readme_path.read_text()
        new_content = "New tools content"

        # Update section and apply changes
        file_manager.update_readme_section('tools', new_content)
        result = file_manager.apply_changes()

        assert result == True

        # Check that original file was updated
        updated_content = readme_path.read_text()
        assert updated_content != original_content
        assert new_content in updated_content
        assert "Old tools content here" not in updated_content

    print("✓ test_apply_changes")


def test_rollback_changes():
    """Test rolling back changes from backup."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        readme_path = temp_path / "README.md"
        original_content = readme_path.read_text()

        # Update section and apply changes
        file_manager.update_readme_section('tools', 'New content')
        file_manager.apply_changes()

        # Verify content changed
        updated_content = readme_path.read_text()
        assert updated_content != original_content

        # Rollback changes
        result = file_manager.rollback_changes()
        assert result == True

        # Verify content restored
        restored_content = readme_path.read_text()
        assert restored_content == original_content

    print("✓ test_rollback_changes")


def test_cleanup_staging():
    """Test staging cleanup."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        # Create staging files
        file_manager.update_readme_section('tools', 'New content')
        staging_path = list(file_manager.staging_files.values())[0]
        backup_dir = file_manager.backup_dir

        assert staging_path.exists()
        assert backup_dir.exists()
        assert len(file_manager.staging_files) > 0

        # Cleanup without removing backups
        file_manager.cleanup_staging(keep_backups=True)

        assert not staging_path.exists()  # Staging file removed
        assert backup_dir.exists()  # Backup directory kept
        assert len(file_manager.staging_files) == 0

        # Create new staging and cleanup with backup removal
        file_manager.update_readme_section('tools', 'Another content')
        file_manager.cleanup_staging(keep_backups=False)

        assert not file_manager.backup_dir.exists()  # Backup directory removed

    print("✓ test_cleanup_staging")


def test_operations_log():
    """Test operations logging."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        # Perform operations
        file_manager.update_readme_section('tools', 'New content')
        file_manager.apply_changes()

        log = file_manager.get_operations_log()

        assert len(log) > 0
        assert any("staging directory" in entry.lower() for entry in log)
        assert any("backed up" in entry.lower() for entry in log)
        assert any("created staging file" in entry.lower() for entry in log)
        assert any("applied changes" in entry.lower() for entry in log)

    print("✓ test_operations_log")


def test_get_staging_preview():
    """Test staging file preview."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        readme_path = temp_path / "README.md"
        new_content = "Preview content"

        # No staging file yet
        preview = file_manager.get_staging_preview(readme_path)
        assert preview is None

        # Create staging file
        file_manager.update_readme_section('tools', new_content)
        preview = file_manager.get_staging_preview(readme_path)

        assert preview is not None
        assert new_content in preview

    print("✓ test_get_staging_preview")


def test_section_manager_extract_content():
    """Test SectionManager content extraction."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        section_manager = SectionManager(config)

        content = create_test_readme_content()

        # Extract tools section
        tools_content = section_manager.extract_section_content(content, 'tools')
        assert tools_content is not None
        assert "Old tools content here" in tools_content

        # Extract resources section
        resources_content = section_manager.extract_section_content(content, 'resources')
        assert resources_content is not None
        assert "Old resources content here" in resources_content

        # Extract non-existent section
        unknown_content = section_manager.extract_section_content(content, 'unknown')
        assert unknown_content is None

    print("✓ test_section_manager_extract_content")


def test_section_manager_validate_markers():
    """Test SectionManager marker validation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        section_manager = SectionManager(config)

        # Valid content
        valid_content = create_test_readme_content()
        results = section_manager.validate_section_markers(valid_content)

        assert 'tools' in results
        assert 'resources' in results
        assert len(results['tools']) == 0  # No errors
        assert len(results['resources']) == 0  # No errors

        # Invalid content (missing end marker)
        invalid_content = """
        <!-- START TOOLS -->
        Content without end marker
        """
        results = section_manager.validate_section_markers(invalid_content)
        assert len(results['tools']) > 0  # Should have errors
        assert any("not found" in error for error in results['tools'])

    print("✓ test_section_manager_validate_markers")


def test_section_manager_generate_markers():
    """Test SectionManager marker generation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        section_manager = SectionManager(config)

        start_marker, end_marker = section_manager.generate_section_markers('tools')

        assert start_marker == "<!-- START TOOLS -->"
        assert end_marker == "<!-- END TOOLS -->"

        start_marker, end_marker = section_manager.generate_section_markers('custom')
        assert start_marker == "<!-- START CUSTOM -->"
        assert end_marker == "<!-- END CUSTOM -->"

    print("✓ test_section_manager_generate_markers")


def test_backup_manager_timestamped_backup():
    """Test BackupManager timestamped backup creation."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        readme_path = temp_path / "README.md"
        original_content = readme_path.read_text()

        # Create timestamped backup
        backup_path = BackupManager.create_timestamped_backup(readme_path)

        assert backup_path.exists()
        assert backup_path.read_text() == original_content
        assert backup_path.name.startswith("README_")
        assert backup_path.name.endswith(".md")

        # Test backup with custom directory
        custom_backup_dir = temp_path / "custom_backups"
        backup_path2 = BackupManager.create_timestamped_backup(readme_path, custom_backup_dir)

        assert backup_path2.parent == custom_backup_dir
        assert backup_path2.exists()

    print("✓ test_backup_manager_timestamped_backup")


def test_backup_manager_restore():
    """Test BackupManager restore functionality."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        readme_path = temp_path / "README.md"
        original_content = readme_path.read_text()

        # Create backup and modify original
        backup_path = BackupManager.create_timestamped_backup(readme_path)
        readme_path.write_text("Modified content")

        # Restore from backup
        result = BackupManager.restore_from_backup(backup_path, readme_path)

        assert result == True
        assert readme_path.read_text() == original_content

        # Test restore from non-existent backup
        try:
            BackupManager.restore_from_backup(temp_path / "nonexistent.backup", readme_path)
            assert False, "Should have raised FileManagerError"
        except FileManagerError:
            pass  # Expected

    print("✓ test_backup_manager_restore")


def test_backup_manager_list_backups():
    """Test BackupManager backup listing."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        readme_path = temp_path / "README.md"

        # No backups initially
        backups = BackupManager.list_backups(readme_path)
        assert len(backups) == 0

        # Create some backups
        import time
        backup1 = BackupManager.create_timestamped_backup(readme_path)
        time.sleep(1.1)  # Ensure different timestamps
        backup2 = BackupManager.create_timestamped_backup(readme_path)

        backups = BackupManager.list_backups(readme_path)
        assert len(backups) == 2
        assert backup1 in backups
        assert backup2 in backups
        # Should be sorted by timestamp (most recent first)
        assert backups[0].name >= backups[1].name

    print("✓ test_backup_manager_list_backups")


def test_file_manager_error_handling():
    """Test FileManager error handling."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        # Test rollback without backup
        try:
            file_manager.rollback_changes()
            assert False, "Should have raised FileManagerError"
        except FileManagerError as e:
            assert "No backup directory" in str(e)

        # Test section replacement with missing markers
        content = "Content without markers"
        try:
            file_manager._replace_section_content(
                content, "<!-- MISSING -->", "<!-- END -->", "new"
            )
            assert False, "Should have raised FileManagerError"
        except FileManagerError as e:
            assert "not found" in str(e)

    print("✓ test_file_manager_error_handling")


def test_file_manager_integration():
    """Test complete FileManager workflow integration."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        create_test_project_structure(temp_path)

        config = DocumentationConfig.from_project_root(temp_path)
        file_manager = FileManager(config)

        readme_path = temp_path / "README.md"
        original_content = readme_path.read_text()

        # Complete workflow: update -> apply -> rollback
        new_tools = "Integrated tools content"
        new_resources = "Integrated resources content"

        # Update both sections
        file_manager.update_readme_section('tools', new_tools)
        file_manager.update_readme_section('resources', new_resources)

        # Apply changes
        file_manager.apply_changes()

        # Verify changes applied
        updated_content = readme_path.read_text()
        # At least one section should be updated and content should change
        tools_updated = new_tools in updated_content
        resources_updated = new_resources in updated_content
        assert tools_updated or resources_updated, f"Neither section updated. Tools: {tools_updated}, Resources: {resources_updated}"
        assert original_content != updated_content

        # Rollback
        file_manager.rollback_changes()

        # Verify rollback worked
        restored_content = readme_path.read_text()
        assert restored_content == original_content

        # Cleanup
        file_manager.cleanup_staging(keep_backups=False)

        # Verify log has all operations
        log = file_manager.get_operations_log()
        assert len(log) > 5  # Multiple operations logged

    print("✓ test_file_manager_integration")


def run_all_tests():
    """Run all test functions."""
    test_functions = [
        test_file_manager_initialization,
        test_create_staging_environment,
        test_create_backup,
        test_create_staging_file,
        test_update_readme_section,
        test_replace_section_content,
        test_validate_staging_files,
        test_apply_changes,
        test_rollback_changes,
        test_cleanup_staging,
        test_operations_log,
        test_get_staging_preview,
        test_section_manager_extract_content,
        test_section_manager_validate_markers,
        test_section_manager_generate_markers,
        test_backup_manager_timestamped_backup,
        test_backup_manager_restore,
        test_backup_manager_list_backups,
        test_file_manager_error_handling,
        test_file_manager_integration,
    ]

    passed = 0
    failed = 0

    for test_func in test_functions:
        try:
            test_func()
            passed += 1
        except Exception as e:
            print(f"✗ {test_func.__name__}: {e}")
            failed += 1

    print(f"\nTest Results: {passed} passed, {failed} failed")
    return failed == 0


if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)
