#!/usr/bin/env python3
"""
Simple script to combine Java tools + Python resources and update README.
"""

import re
import json
import sys
import subprocess
from pathlib import Path

def main():
    project_root = Path(__file__).parent.parent
    readme_path = project_root / "README.md"

    print("Generating JSON from both scripts...")

    # Get Python output (better resource descriptions)
    python_result = subprocess.run([
        "python", str(project_root / "scripts" / "update-readme.py"), "--json"
    ], capture_output=True, text=True, cwd=project_root)

    if python_result.returncode != 0:
        print(f"Python script failed: {python_result.stderr}")
        return False

    # Get Java output (better tool parameters)
    java_result = subprocess.run([
        "java", "-cp", "scripts:target/classes:target/quarkus-app/lib/main/*",
        "UpdateReadme", "--json"
    ], capture_output=True, text=True, cwd=project_root)

    if java_result.returncode != 0:
        print(f"Java script failed: {java_result.stderr}")
        return False

    # Parse JSON outputs
    python_data = json.loads(python_result.stdout)
    java_data = json.loads(java_result.stdout)

    # Combine: Java tools + Python resources
    combined_tools = java_data["tools"]
    combined_resources = python_data["resources"]

    print(f"Combined: {len(combined_tools)} Java tools + {len(combined_resources)} Python resources")

    # Generate formatted content
    tools_content = generate_tools_section(combined_tools)
    resources_content = generate_resources_section(combined_resources)

    # Update README
    if not readme_path.exists():
        print(f"README.md not found at {readme_path}")
        return False

    content = readme_path.read_text()

    # Update tools section
    tools_pattern = r'<!--- Tools generated by .* -->'
    tools_end = '<!--- End of tools generated section -->'
    tools_marker = '<!--- Tools generated by update-combined-simple.py -->'

    print(f"[DEBUG] Looking for tools pattern: {tools_pattern}", file=sys.stderr)
    start_match = re.search(tools_pattern, content)
    if start_match:
        print(f"[DEBUG] Found tools start marker at position {start_match.start()}-{start_match.end()}", file=sys.stderr)
        print(f"[DEBUG] Matched text: {repr(start_match.group())}", file=sys.stderr)
        end_idx = content.find(tools_end)
        if end_idx != -1:
            print(f"[DEBUG] Found tools end marker at position {end_idx}", file=sys.stderr)
            content = (content[:start_match.start()] +
                      tools_marker + '\n\n' +
                      tools_content + '\n\n' +
                      content[end_idx:])
            print("✓ Tools section updated")
        else:
            print(f"[ERROR] Tools end marker not found: '{tools_end}'", file=sys.stderr)
    else:
        print(f"[ERROR] Tools start marker not found with pattern: {tools_pattern}", file=sys.stderr)
        # Try to find what's actually there
        lines = content.split('\n')
        for i, line in enumerate(lines):
            if 'Tools generated by' in line:
                print(f"[DEBUG] Found tools marker at line {i+1}: {repr(line)}", file=sys.stderr)

    # Update resources section
    resources_pattern = r'<!--- Resources generated by .* -->'
    resources_end = '<!--- End of resources generated section -->'
    resources_marker = '<!--- Resources generated by update-combined-simple.py -->'

    print(f"[DEBUG] Looking for resources pattern: {resources_pattern}", file=sys.stderr)
    start_match = re.search(resources_pattern, content)
    if start_match:
        print(f"[DEBUG] Found resources start marker at position {start_match.start()}-{start_match.end()}", file=sys.stderr)
        print(f"[DEBUG] Matched text: {repr(start_match.group())}", file=sys.stderr)
        end_idx = content.find(resources_end)
        if end_idx != -1:
            print(f"[DEBUG] Found resources end marker at position {end_idx}", file=sys.stderr)
            content = (content[:start_match.start()] +
                      resources_marker + '\n\n' +
                      resources_content + '\n\n' +
                      content[end_idx:])
            print("✓ Resources section updated")
        else:
            print(f"[ERROR] Resources end marker not found: '{resources_end}'", file=sys.stderr)
    else:
        print(f"[ERROR] Resources start marker not found with pattern: {resources_pattern}", file=sys.stderr)
        # Try to find what's actually there
        lines = content.split('\n')
        for i, line in enumerate(lines):
            if 'Resources generated by' in line:
                print(f"[DEBUG] Found resources marker at line {i+1}: {repr(line)}", file=sys.stderr)

    # Write updated README
    readme_path.write_text(content)
    print("✓ README.md updated with combined approach!")
    return True

def generate_tools_section(tools):
    """Generate tools section using Java data (better parameters)"""
    if not tools:
        return "No tools found."

    lines = []

    # Group tools by category
    categories = {
        'Entity Management': [t for t in tools if any(x in t['name'] for x in ['create_entities', 'delete_entities'])],
        'Relationship Management': [t for t in tools if any(x in t['name'] for x in ['create_relations', 'delete_relations'])],
        'Observation Management': [t for t in tools if any(x in t['name'] for x in ['add_observations', 'delete_observations'])],
        'Graph Operations': [t for t in tools if any(x in t['name'] for x in ['read_graph', 'search_nodes', 'open_nodes'])]
    }

    for category, category_tools in categories.items():
        if not category_tools:
            continue

        lines.append("<details>")
        lines.append(f"<summary><b>{category}</b></summary>")
        lines.append("")

        for tool in category_tools:
            lines.extend(format_tool(tool))

        lines.append("</details>")
        lines.append("")

    return '\n'.join(lines)

def generate_resources_section(resources):
    """Generate resources section using Python data (better descriptions)"""
    if not resources:
        return "No resources found."

    lines = ["<details>", "<summary><b>Memory Resources</b></summary>", ""]

    for resource in resources:
        lines.extend(format_resource(resource))

    lines.extend(["</details>", ""])
    return '\n'.join(lines)

def format_tool(tool):
    """Format a single tool"""
    lines = [
        "<!-- NOTE: This has been generated via update-combined-simple.py -->",
        "",
        f"- **{tool['name']}**",
        f"  - Title: {tool['title']}",
        f"  - Description: {tool['description']}"
    ]

    if tool.get('parameters'):
        lines.append("  - Parameters:")
        for param in tool['parameters']:
            required_text = "" if param.get('required', True) else ", optional"
            lines.append(f"    - `{param['name']}` ({param['type']}{required_text}): {param['description']}")
    else:
        lines.append("  - Parameters: None")

    lines.append(f"  - Read-only: **{str(tool.get('read_only', False)).lower()}**")
    lines.append("")

    return lines

def format_resource(resource):
    """Format a single resource"""
    return [
        "<!-- NOTE: This has been generated via update-combined-simple.py -->",
        "",
        f"- **{resource['uri']}**",
        f"  - Title: {resource['title']}",
        f"  - Description: {resource['description']}",
        ""
    ]

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
